services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth-api:
    build:
      context: ./AuthSefviceApi1
      dockerfile: AuthSefviceApi1/Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:5212
    restart: unless-stopped
    ports:
      - "5212:5212"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./chat-front
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - auth-api

volumes:
  postgres_data: