apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: kt2-k8s
type: Opaque
stringData:
   JWT__KEY: nMKUC4OOCTX0B7EtOXgWkBlWnEnOvut7PVhxN2kzVoT
   CONNECTIONSTRINGS__DEFAULTCONNECTION: Host=postgres-service;Port=5432;Database=authdb;Username=postgres;Password=1234
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: kt2-k8s
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "1234"
  POSTGRES_DB: authdb